[package]
name = "sr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libffi = "3.2.0"
thiserror = "1.0.40"

[build-dependencies]
bindgen = "0.66.1"
